apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: teamonboard
  name: teamonboard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: teamonboard
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: teamonboard
    spec:
      containers:
      - image: forge/teamonboard:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "spring_profiles_active"
          value: kubernetes
        name: teamonboard
        volumeMounts:
          - name: "conf"
            mountPath: /conf
        ports:
        - containerPort: 8182
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      volumes:
      - name: conf
        secret:
          secretName: tob-conf-file
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
